// <auto-generated />
namespace pmboard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init61));
        
        string IMigrationMetadata.Id
        {
            get { return "201710300856342_init61"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
